version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: second-brain-db
    environment:
      POSTGRES_DB: secondbrain
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"